### ISSUE TITLE
HTTP endpoint doesn't work on a specific website

### ISSUE THREAD

**Issue by metalwarrior665** [apify/proxy-chain#107]
This is a report from our user.

Response
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 11 Feb 2021 16:37:41 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
<
* Connection #0 to host proxy.apify.com left intact
Internal error in proxy server
```

Commentary
```
it also works on this website if I use https instead of http
the url works with curl without the proxy
```

**Comment by jancurn** [comment]
It's because http://www.aigroup.com.au/ returns this HTTP respone:

<img width="835" alt="Screen Shot 2021-02-13 at 23 53 12" src="https://user-images.githubusercontent.com/10612996/107863734-f74a0c00-6e56-11eb-85a2-aadecb070ee4.png">

The `Server` key missing value, and Node.js HTTP parser probably fails on that with: 

```
ProxyServer[8000]: 2 | Target socket failed: Error: Parse Error: Invalid header token
    at Socket.socketOnData (_http_client.js:476:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

There really isn't an easy fix, and most websites use HTTPS or valid HTTP repsonse, so this is a niche problem.

**Comment by szmarczak** [comment]
We can fix this partially by setting `insecureHTTPParser` to `true` in client and omitting invalid headers in server.
