### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by iJoris** [apify/proxy-chain#170]
Trying to use proxy-chain for puppeteer results in ERR_TUNNEL_CONNECTION_FAILED.

Even when I use the anonymizeProxy function for my own windows manual proxy I get an SSL error.
It seems that HTTPS sites do not work, HTTP works.

Usage:
```
let proxy = "http://user_name:pass_word_12345-67@proxy.server.com:1111/"
let result = await proxyChain.anonymizeProxy(proxy);
console.log(result);
```

result = http://127.0.0.1:62549

I pass that as args.push('--proxy-server=' + result);
Puppeteer gives me then an ERR_TUNNEL_CONNECTION_FAILED

If I use the proxy in windows HTTP sites seem to work. HTTPS not.

Example code:
```
const puppeteer = require("puppeteer");
const proxyChain = require("proxy-chain");

(async () => {
    let proxy =
  "IP:PORT";
  let resolved = await proxyChain.anonymizeProxy(proxy);
  let proxyserver = '--proxy-server=' + resolved.replace('http://', '');

  const browser = await puppeteer.launch({
    args: [proxyserver],
    headless: false,
    ignoreHTTPSErrors: true,
  });

  const page = await browser.newPage();
  await page.goto("https://www.whatismyip.com/");
  await page.screenshot({ path: "example.png" });
})();
```

When using verbose I get the following output:

```
ProxyServer[63005]: Listening...
ProxyServer[63005]: 1 | !!! Handling CONNECT www.google.com:443 HTTP/1.1
ProxyServer[63005]: 1 | Using upstream proxy http://username:<redacted>@IP:PORT/
ProxyServer[63005]: 1 | Using HandlerTunnelChain
ProxyServer[63005]: 1 | Connecting to upstream proxy...
ProxyServer[63005]: 1 | Target socket assigned
ProxyServer[63005]: 2 | !!! Handling CONNECT www.google.com:443 HTTP/1.1
ProxyServer[63005]: 2 | Using upstream proxy http://username:<redacted>@IP:PORT/
ProxyServer[63005]: 2 | Using HandlerTunnelChain
ProxyServer[63005]: 2 | Connecting to upstream proxy...
ProxyServer[63005]: 2 | Target socket assigned
ProxyServer[63005]: 3 | !!! Handling CONNECT accounts.google.com:443 HTTP/1.1
ProxyServer[63005]: 3 | Using upstream proxy http://username:<redacted>@IP:PORT/
ProxyServer[63005]: 3 | Using HandlerTunnelChain
ProxyServer[63005]: 3 | Connecting to upstream proxy...
ProxyServer[63005]: 3 | Target socket assigned
ProxyServer[63005]: 1 | Target request failed: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)     
ProxyServer[63005]: 1 | Connection lost, sending 502 to client
ProxyServer[63005]: 1 | Target socket failed: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)    
ProxyServer[63005]: 1 | Source already received a response, just destroying the socket...
ProxyServer[63005]: 1 | Closing handler
ProxyServer[63005]: 1 | !!! Closed and removed from server
```

**Comment by babyrusa** [comment]
having the same issue here. Testing this on local

**Comment by szmarczak** [comment]
Can you confirm whether if this occurs as well when configuring the proxy manually in e.g. firefox?

**Comment by iJoris** [comment]
Problem was my local firewall.
